### PR TITLE
Custom mem read

### PR DESCRIPTION
**Pull request by grahambates**
I've made a change to the read-memory command in FS-UAE and [WinUAE](https://github.com/BartmanAbyss/WinUAE/pull/5) to allow reading from custom register addresses. This unblocks a few features in the debugger:

Variables pointing to addresses in this range will now correctly display their values:

image

You can read custom addresses in the `Amiga: View memory` command:

image

I've also implemented a new panel to list these alongside CPU registers when debugging.

image

### CODE REVIEW

**Comment by BartmanAbyss** [comment]
cool. can you support `CustomSpecial.pth`, `CustomSpecial.ptl` to combine pointer registers into one as in https://github.com/BartmanAbyss/vscode-amiga-debug/blob/master/src/client/debugger/customregs.tsx#L84 ?

**Comment by grahambates** [comment]
I've made this change and also refactored a bit to move a bit more logic into the `BaseNode` class to eliminate some repetition around value formatting etc.

**Comment by grahambates** [comment]
We could definitely make more use of the tree view to group related fields and extract bit components from register values. I implemented something similar on [The Other Extension](https://github.com/prb28/vscode-amiga-assembly) 🙂:

image

I can look at porting this if you're interested (maybe as a separate PR). It's a bit of a different implementation because we use the variables list for registers, but I can definitely reuse the grouping logic. I'm guessing we'd want it in the profiler register list too.

**Comment by BartmanAbyss** [comment]
sure. that sounds fine. I'm doing something similar but more hard-coded for the DMA/blitter tooltips and the screen tooltips.
probably a bit harder for the profiler register list because I had to switch to a virtual list due to performance reasons,

**Pull request merged**
