### PR TITLE
Cycle decoration improvements

### PR DESCRIPTION
**Pull request by grahambates**
- Increase width to handle 3 digit ranges
- Add byte size on hover
- Add horizontal rules between sections in hover
- Prevent misalignment / jumping while editing due to delay updating counts. Every line always has an 'empty' decoration to add horizontal space and the actual counts are positioned in front of this.

### CODE REVIEW

**Comment by BartmanAbyss** [comment]
Nice! This was bothering mee, too, but I never got around to doing something about it :)

**Comment by BartmanAbyss** [comment]
Btw, is there a way to immediately add that empty space? when cyling through assembly files in the explorer, I still see the text on the left before the space is inserted for about 0.5s or so..

**Comment by BartmanAbyss** [comment]
Also, I was just testing it with your M68000 assembly extension, and it parses and colorizes correctly, but shows this error: 
```
[{
	"resource": "/c:/Users/Chuck/Documents/Visual_Studio_Code/vscode-amiga-debug/template/support/depacker_doynax_vasm.asm",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "14",
	"severity": 8,
	"message": "could not open <C:\\Users\\Chuck\\AppData\\Local\\Temp\\a.out> for output",
	"source": "vasm",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
```

**Comment by grahambates** [comment]
> Btw, is there a way to immediately add that empty space

The space should be added first. Maybe it's just down to how the rendered view updates. I'll have another look at this though.

**Comment by BartmanAbyss** [comment]
It appears sooner than the cycle count, but still a delay after the document is shown.

**Comment by grahambates** [comment]
Thanks for flagging the issue on my extension. It looks like Vasm is failing when trying to assemble to a temporary file, which it does to generate diagnostics. This might be permission related.

**Comment by BartmanAbyss** [comment]
Maybe it runs too often, even parallel and multiple processes try to access `a.out`? In my extension I give the output files a unique temp name each run.

**Comment by grahambates** [comment]
Setting the empty decorations is the first thing that happens on `onDidOpenTextDocument` and `onDidChangeTextDocument`. I'm guessing it's the render update that's slow.

**Comment by BartmanAbyss** [comment]
Yeah it's a bit strange as the text comes out fully colorized at the same time.
Does it look the same for you? (sorry for crappy video quality)
https://user-images.githubusercontent.com/19374186/204906280-da742502-f5d5-4ab7-8010-c032693c4ded.mp4

**Comment by grahambates** [comment]
Yeah that's pretty much what it looks like for me. I'm not sure there's much we can do about it.

On the m68k diagnostics thing, I suspect it might be Windows specific. The thing is though, we really don't need two extensions assembling the same file and generating the same diagnostics! When it does run successfully you just end up with duplicate messages:

image

I'm going to open a PR to have it disable the `provideDiagnostics` config setting.

**Comment by grahambates** [comment]
Looks like the delay is a known issue:

https://github.com/microsoft/vscode/issues/136241

**Comment by BartmanAbyss** [comment]
Alrighty. No more we can do then.

**Pull request merged**
