### PR TITLE
Vasm fixes

### PR DESCRIPTION
**Pull request by grahambates**
- Update Mac/Linux Vasm to 1.9a. Needed for `Llo` / `Lni` options used in syntax check
- Set CWD for VASM to workspace dir. This fixes relative `INCLUDE` / `INCDIR` directives.

### CODE REVIEW

**Comment by BartmanAbyss** [comment]
Have you seen that the bundled Windows version of VASM has been modified to change the section names? Is this still necessary after your textSection() modifications? https://github.com/davidcanadas/vasm-m68k-mot-win32

**Comment by grahambates** [comment]
No I hadn't realised it was patched. I'd been playing with other options to get it to recognise code sections not named `.text` [here](https://github.com/BartmanAbyss/vscode-amiga-debug/commit/c89d53fcd5c1fe63161d38878ef838a569de265b), but that's not in this PR.

I'll update with the patched version instead.

**Comment by grahambates** [comment]
Something else I wanted to run past you:

I was also looking at getting unwind working for profiling assembly code. Currently because there's no `objdump` data for assembly sources, the entries in the unwind table are always invalid resulting in a flat flame graph. You should be able to get the parent frame by just reading directly up the stack in assembly because you're typically not passing args on the stack. A default value of `4/15/-1/-4` seems to make this work. [Here's](https://github.com/BartmanAbyss/vscode-amiga-debug/commit/f5920906cee79d65eca3d5d9dc3b49961bfadf87) my implementation.

Are there any downsides to this that I'm missing? If there are other values in the stack that don't map to an address in the text section they get ignored anyway.

**Comment by BartmanAbyss** [comment]
This will probably not work when functions save registers on the stack. I've been thinking about this problem too, but haven't come up with an automated way.
It should work for normal functions that don't modify the stack pointer with `.cfi_startproc` and `.cfi_endproc` (gnu assembly directives). When functions modify the stack pointer I manually annotated assembly source with `.cfi_adjust_cfa_offset` directives (see
https://github.com/BartmanAbyss/vscode-amiga-debug/blob/master/template/support/gcc8_a_support.s )

**Comment by grahambates** [comment]
Yeah there will for sure be cases where it doesn't work if you're doing stuff with the stack, but I was thinking this would be a better default.

**Comment by BartmanAbyss** [comment]
Have you tried if that works without any negative sideeffects? If so, sure, why not.

**Pull request merged**
